### ISSUE TITLE
SVG data in CSS?

### ISSUE THREAD

**Issue by tomByrer** [mxstbr/sharing#27]
If there is more than 1 webpage using the same social icons, I think [SVG would be better in the CSS](http://calendar.perfplanet.com/2014/tips-for-optimising-svg-delivery-for-the-web/)?

**Comment by peter-mouland** [comment]
for responsive site, do the icons ever need to be resized, or do the colours ever need changing etc?

I prefer svg's inline (in the html) so the classnames and css can change them like normal DOM.  

when you import svg's into jsx (ie. react) you still gain from minimal http requests as the svg is in the js code itself (once compiled)

**Comment by mxstbr** [comment]
I kinda like the SVG-in-CSS approach because it'll also work much better for emails I think? I'd appreciate a PR implementing a first idea!

**Comment by peter-mouland** [comment]
the only downside with the base64 approach is if the same icon is needed twice, but with a slight styling tweak (e.g. smaller / mono-chrome for mobile or bigger / full-colour for retina), you then have 2 sets of base64 icons in the css.  Which is why inline is better.

I think the base64 still treats its as svg, so a background image no better than inline for emails (i would expect!)

but like i say, if you're not changing the icons, ever, then it's not a problem.

**Comment by olets** [comment]
@tomByrer the big reason to use inlined svgs here is it means we can style them with css. As @peter-mouland says, this it lets you change colors, sizes, etc. In the case of sharingicons.io, using inlined css is how it supports the four styles set in the "icon" section of the UI (outline, outline in circle, solid, solid in circle via the the `stroke` and `fill` values). Sure there are other ways around it (sites have been using similar design elements since well before svg was widely supported) but this is both the most compact and the most flexible.

**Comment by olets** [comment]
Oh missed the email aspect of this question. I haven't tested this. As of December, [svg support in email was spotty](https://css-tricks.com/a-guide-on-svg-support-in-email/). This is something to look into. Do we have anyone here who's paying for Litmus or Email On Acid?

**Comment by tomByrer** [comment]
Styling via CSS is a solid point.
Sorry, no email testing here, aside from manual.

**Comment by olets** [comment]
Closing this and moving the email question over to #61
